import type { HastPluginDefinition, HastVisitorContext, HastNode } from 'satteri'
import {
	type BundledShikiTheme,
	loadShikiTheme,
	ExpressiveCode,
	type ExpressiveCodeConfig,
	ExpressiveCodeTheme,
	type ExpressiveCodeBlockOptions,
	ExpressiveCodeBlock,
	type ExpressiveCodeThemeInput,
} from 'expressive-code'
import type { Element } from 'expressive-code/hast'
import { getCodeBlockInfo } from './utils'

export * from 'expressive-code'

export type SatteriExpressiveCodeOptions = Omit<ExpressiveCodeConfig, 'themes'> & {
	/**
	 * The color themes that should be available for your code blocks.
	 *
	 * CSS variables will be generated for all themes, allowing to select the theme to display
	 * using CSS. If you specify one dark and one light theme, a `prefers-color-scheme` media query
	 * will also be generated by default. You can customize this to match your site's needs
	 * through the `useDarkModeMediaQuery` and `themeCssSelector` options.
	 *
	 * The following item types are supported in this array:
	 * - any theme name bundled with Shiki (e.g. `dracula`)
	 * - any theme object compatible with VS Code or Shiki (e.g. imported from an NPM theme package)
	 * - any ExpressiveCodeTheme instance (e.g. using `ExpressiveCodeTheme.fromJSONString(...)`
	 *   to load a custom JSON/JSONC theme file yourself)
	 *
	 * Defaults to `['github-dark', 'github-light']`, two themes bundled with Shiki.
	 */
	themes?: ThemeObjectOrShikiThemeName[] | undefined
	/**
	 * The number of spaces that should be used to render tabs. Defaults to 2.
	 *
	 * Any tabs found in code blocks in your markdown/MDX documents will be replaced
	 * with the specified number of spaces. This ensures that the code blocks are
	 * rendered consistently across browsers and platforms.
	 *
	 * If you want to preserve tabs in your code blocks, set this option to 0.
	 */
	tabWidth?: number | undefined
	/**
	 * This optional function provides support for multi-language sites by allowing you
	 * to customize the locale used for a given code block.
	 *
	 * The function is called with an object containing the following properties:
	 * - `input`: Block data for the `ExpressiveCodeBlock` constructor.
	 * - `document`: A `SatteriExpressiveCodeDocument` object with information about the parent document.
	 */
	getBlockLocale?: (({ input, document }: { input: ExpressiveCodeBlockOptions; document: SatteriExpressiveCodeDocument }) => string | undefined | Promise<string | undefined>) | undefined
	/**
	 * This optional function allows you to customize how `ExpressiveCodeBlock`
	 * instances are created from code blocks found in the Markdown document.
	 *
	 * The function is called with an object containing the following properties:
	 * - `input`: Block data for the `ExpressiveCodeBlock` constructor.
	 * - `document`: A `SatteriExpressiveCodeDocument` object with information about the parent document.
	 *
	 * The function is expected to return an `ExpressiveCodeBlock` instance
	 * or a promise resolving to one.
	 */
	customCreateBlock?:
		| (({ input, document }: { input: ExpressiveCodeBlockOptions; document: SatteriExpressiveCodeDocument }) => ExpressiveCodeBlock | Promise<ExpressiveCodeBlock>)
		| undefined
	/**
	 * This advanced option allows you to influence the rendering process by creating
	 * your own `ExpressiveCode` instance or processing the base styles and JS modules
	 * added to every page.
	 *
	 * The return value will be cached and used for all code blocks on the site.
	 */
	customCreateRenderer?: ((options: SatteriExpressiveCodeOptions) => Promise<SatteriExpressiveCodeRenderer> | SatteriExpressiveCodeRenderer) | undefined
}

export type ThemeObjectOrShikiThemeName = BundledShikiTheme | ExpressiveCodeTheme | ExpressiveCodeThemeInput

export type SatteriExpressiveCodeDocument = {
	/**
	 * The source text of the document being processed.
	 */
	source: string
	/**
	 * The filename of the document being processed.
	 */
	filename: string
}

export type SatteriExpressiveCodeRenderer = {
	ec: ExpressiveCode
	baseStyles: string
	themeStyles: string
	jsModules: string[]
}

/**
 * Creates an `ExpressiveCode` instance using the given `options`,
 * including support to load themes bundled with Shiki by name.
 *
 * Returns the created `ExpressiveCode` instance together with the base styles and JS modules
 * that should be added to every page.
 */
export async function createRenderer(options: SatteriExpressiveCodeOptions = {}): Promise<SatteriExpressiveCodeRenderer> {
	const { themes, ...ecOptions } = options
	const loadedThemes =
		themes &&
		(await Promise.all(
			(Array.isArray(themes) ? themes : [themes]).map(async (theme) => {
				const mustLoadTheme = theme !== undefined && !(theme instanceof ExpressiveCodeTheme)
				const optLoadedTheme = mustLoadTheme ? new ExpressiveCodeTheme(typeof theme === 'string' ? await loadShikiTheme(theme) : theme) : theme
				return optLoadedTheme
			})
		))
	const ec = new ExpressiveCode({
		themes: loadedThemes,
		...ecOptions,
	})
	const baseStyles = await ec.getBaseStyles()
	const themeStyles = await ec.getThemeStyles()
	const jsModules = await ec.getJsModules()

	return {
		ec,
		baseStyles,
		themeStyles,
		jsModules,
	}
}

/**
 * Creates a satteri HAST plugin that processes code blocks using Expressive Code.
 *
 * This is the satteri equivalent of `rehype-expressive-code`. It returns a
 * `HastPluginDefinition` that can be passed to satteri's `hastPlugins` option.
 *
 * @example
 * ```ts
 * import { markdownToHtml } from 'satteri'
 * import { satteriExpressiveCode } from 'satteri-expressive-code'
 *
 * const plugin = await satteriExpressiveCode({ themes: ['github-dark'] })
 * const html = await markdownToHtml(source, { hastPlugins: [plugin] })
 * ```
 */
export async function satteriExpressiveCode(options: SatteriExpressiveCodeOptions = {}): Promise<HastPluginDefinition> {
	const { tabWidth = 2, getBlockLocale, customCreateRenderer, customCreateBlock } = options

	const renderer = await (customCreateRenderer ?? createRenderer)(options)
	const { ec, baseStyles, themeStyles, jsModules } = renderer

	// Satteri dispatches all matched visitor calls synchronously before resolving
	// any async results. This means Set-based deduplication won't work across
	// concurrent async visitors. Instead, we use a synchronous counter (incremented
	// before the first await) to ensure only the first code block gets base assets.
	let blockIndex = 0

	return {
		name: 'satteri-expressive-code',
		element: {
			filter: ['pre'],
			async visit(node: Readonly<HastNode>, ctx: HastVisitorContext): Promise<HastNode | void> {
				const element = node as unknown as Element
				const codeBlockInfo = getCodeBlockInfo(element)
				if (!codeBlockInfo) return

				// Claim this block's index synchronously before any await
				const isFirstBlock = blockIndex === 0
				blockIndex++

				let normalizedCode = codeBlockInfo.text
				if (tabWidth > 0) normalizedCode = normalizedCode.replace(/\t/g, ' '.repeat(tabWidth))

				const document: SatteriExpressiveCodeDocument = {
					source: ctx.source,
					filename: ctx.filename,
				}

				const input: ExpressiveCodeBlockOptions = {
					code: normalizedCode,
					language: codeBlockInfo.lang || '',
					meta: codeBlockInfo.meta || '',
					parentDocument: {
						sourceFilePath: ctx.filename,
					},
				}

				if (getBlockLocale) {
					input.locale = await getBlockLocale({ input, document })
				}

				const codeBlock = customCreateBlock ? await customCreateBlock({ input, document }) : new ExpressiveCodeBlock(input)

				const { renderedGroupAst, styles } = await ec.render(codeBlock)

				const extraElements: Element['children'] = []
				const stylesToPrepend: string[] = []

				// Base styles and JS modules are only injected on the first block
				if (isFirstBlock) {
					if (baseStyles) stylesToPrepend.push(baseStyles)
					if (themeStyles) stylesToPrepend.push(themeStyles)
				}

				// Per-block styles are always included
				for (const style of styles) {
					stylesToPrepend.push(style)
				}

				if (stylesToPrepend.length) {
					extraElements.push({
						type: 'element',
						tagName: 'style',
						properties: {},
						children: [{ type: 'text', value: stylesToPrepend.join('') }],
					})
				}

				if (isFirstBlock) {
					jsModules.forEach((moduleCode) => {
						extraElements.push({
							type: 'element',
							tagName: 'script',
							properties: { type: 'module' },
							children: [{ type: 'text', value: moduleCode }],
						})
					})
				}

				if (extraElements.length) {
					const firstChild = renderedGroupAst.children.length > 0 ? renderedGroupAst.children[0] : undefined
					const firstChildIsStyle = firstChild?.type === 'element' && ['style', 'link'].includes(firstChild?.tagName)
					const insertIndex = firstChildIsStyle ? 1 : 0
					renderedGroupAst.children.splice(insertIndex, 0, ...extraElements)
				}

				return renderedGroupAst as unknown as HastNode
			},
		},
	}
}

export default satteriExpressiveCode
